### PR TITLE
Fixes #67 wrong import in security interceptors

### LINKED ISSUE #67: Wrong comparison
Not disclosed atm.

### PR DESCRIPTION
**Pull request by pith**
Change interceptor implementation to be more robust. Now `AND` is the default case.
Add unit tests on interceptors.

### CODE REVIEW

**Comment by adrienlauer** [comment]
LGTM

**Comment by ydautremay** [comment]
I guess I can send my code to the bin now :(

**Comment by pith** [comment]
Sorry @ydautremay, I didn't know you started to work on it. Did you have a different approach fixing this ? 

I also noticed that the interceptors search the annotations only on the implementation class. We may want to also check the interface or super class.

**Comment by ydautremay** [comment]
I had begun writing the tests (TDD rulez :D)
Maybe the check of rights could be marked on the interface/super class. Overriden if annotation present in the implementation. We should wonder if it makes sense functionnally.

**Comment by pith** [comment]
Ok, I will create a new issue to discuss this and merge this one.

**Comment by adrienlauer** [comment]
Sorry @ydautremay, i asked @pith to do this asap because @RicBon wanted to contribute on it but finally didn't have the time. Sadly, I didn't checked if someone was already working on it.

Regarding the interface/implementation annotation behavior, I think we badly need to review existing all annotation detection code and implement a unique, documented behavior. When a different behavior is needed, we should also document how it diverges from the standard detection mechanism. But I don't even know if we need multiple behaviors at all.

**Comment by ydautremay** [comment]
Agreed

**Comment by pith** [comment]
:+1:

**Pull request merged**
