### PR TITLE
Add @ITInstall annotation for IT-only modules

### PR DESCRIPTION
**Pull request by adrienlauer**

### CODE REVIEW

**Comment by adrienlauer** [comment]
We need to install some Guice modules only in IT mode, so Guice won't complain about missing test classes in the main classpath.

**Comment by pith** [comment]
I don't see the use case here. Does the modules bound with `@ITInstall` are in the main classpath not the IT classpath ? Do you have a sample ?

**Comment by adrienlauer** [comment]
@pith Yes they are. Everytime you have some testing tools mixed with main functionality (like in javamail or in business) you may want to install an IT module only when running tests. 

But an @ITInstall annotation proved to be too limited for the javamail case. I finally used conditional installation of module (only when a class is present). So we may remove this annotation.

**Comment by ejemba** [comment]
@adrienlauer :+1:

**Comment by pith** [comment]
Ah ok, I see. It was required by the fusion you made between test modules with core module.

**Pull request merged**
